# Generated by Django 3.1.2 on 2020-12-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=31)),
                ('desc', models.TextField(default='')),
                ('objective', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti'), (3, 'Rt'), (4, 'Jc')])),
                ('pid', models.CharField(default='', max_length=31)),
                ('input_desc', models.TextField(default='')),
                ('output_desc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('author_id', models.IntegerField(default=0)),
                ('evalutaion', models.IntegerField(default=0)),
                ('erase_cnt', models.IntegerField(default=0)),
                ('elapsed_time', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Running'), (3, 'Wrong'), (4, 'Compile Err'), (5, 'Runtime Err'), (6, 'Time Limit Exceed'), (7, 'Out Of Memory')], default=2)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('problem_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problem.probleminput')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
