# Generated by Django 3.1.2 on 2020-10-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_style',
            field=models.IntegerField(choices=[(1, 'Um'), (2, 'Ns'), (3, 'Ft'), (4, 'Pj')]),
        ),
    ]
