# Generated by Django 3.1.2 on 2020-10-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20201030_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_style',
            field=models.IntegerField(choices=[(1, 'Um'), (2, 'Ti'), (3, 'Ef'), (4, 'Jc')]),
        ),
    ]
