# Generated by Django 3.1.2 on 2020-11-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20201031_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problem_style',
            new_name='style',
        ),
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AddField(
            model_name='solution',
            name='erase_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Running'), (3, 'Wrong'), (4, 'Compile Err'), (5, 'Runtime Err'), (6, 'Time Limit Exceed'), (7, 'Out Of Memory')], default=2),
        ),
    ]
