# Generated by Django 3.1.2 on 2020-11-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20201109_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='style',
            field=models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')]),
        ),
    ]
