# Generated by Django 3.1.2 on 2020-11-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20201109_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='style',
            new_name='objective',
        ),
    ]
