# Generated by Django 3.1.2 on 2020-11-11 13:39

import django.contrib.postgres.fields
from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20201110_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='name',
            new_name='input_desc',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='content',
            new_name='source_code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='probleminput',
            name='content',
        ),
        migrations.RemoveField(
            model_name='problemoutput',
            name='content',
        ),
        migrations.AddField(
            model_name='problem',
            name='output_desc',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AddField(
            model_name='problem',
            name='pid',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AddField(
            model_name='probleminput',
            name='test_cases',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=problem.models.get_array_default, size=None),
        ),
        migrations.AddField(
            model_name='problemoutput',
            name='test_cases',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=problem.models.get_array_default, size=None),
        ),
        migrations.AddField(
            model_name='solution',
            name='elapsed_time',
            field=models.IntegerField(default=0),
        ),
    ]
