# Generated by Django 3.1.2 on 2020-11-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_problem_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_desc',
            field=models.TextField(default=''),
        ),
    ]
