# Generated by Django 3.1.2 on 2020-11-12 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_auto_20201111_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='source_code',
            new_name='code',
        ),
    ]
