# Generated by Django 3.1.2 on 2020-11-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_auto_20201112_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probleminput',
            old_name='test_cases',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='problemoutput',
            old_name='test_cases',
            new_name='content',
        ),
    ]
