# Generated by Django 3.1.2 on 2020-11-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_auto_20201114_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
    ]
