# Generated by Django 3.1.2 on 2020-11-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_solution_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminput',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problemoutput',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
