#!/bin/sh

# Check for eslint / pylint command exist
# eslint
eslintCMD=node_modules/.bin/eslint
if ! test -e "$eslintCMD"; then
    echo "\t\033[41mPlease install ESlint\033[0m"
    exit 1
fi
# pylint
which pylint &> /dev/null
if [ "$?" == 1 ] ; then
    echo "\t\033[41mPlease install pylint\033[0m"
    exit 1
fi



# execute eslint
$eslintCMD -c $REPOBASE/.eslintrc.js src/
if [[ "$?" != 0 ]]; then
    echo "\t\033[41mESLint Failed\033[0m"
    exit 1
fi



# execute pylint
cd backend
pylint **/*.py --load-plugins pylint_django
if [[ "$?" != 0 ]]; then
    echo "\t\033[41mPYLint Failed\033[0m"
    exit 1
fi




# execute frontend test
PASS_FRONTEND_TEST=true
yarn test --coverage --watchAll=false
if [[ "$?" != 0 ]]; then
    echo "\t\033[41mREACT TEST Failed\033[0m"
    exit 1
fi



# execute backend test
./backend/local-docker/local-docker-tester-back/init-test.sh
if [[ "$?" != 0 ]]; then
    echo "\t\033[41mDJANGO TEST Failed\033[0m"
    exit 1
fi






exit $?
