# Generated by Django 3.1.2 on 2020-10-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingstyle',
            name='EF_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingstyle',
            name='JC_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingstyle',
            name='TI_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingstyle',
            name='UM_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='default', max_length=21, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='default_path', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codingstyle',
            name='style',
            field=models.IntegerField(choices=[(1, 'Utej'), (2, 'Utec'), (3, 'Utfj'), (4, 'Utfc'), (5, 'Uiej'), (6, 'Uiec'), (7, 'Uifj'), (8, 'Uifc'), (9, 'Mtej'), (10, 'Mtec'), (11, 'Mtfj'), (12, 'Mtfc'), (13, 'Miej'), (14, 'Eiec'), (15, 'Mifj'), (16, 'Mifc')]),
        ),
    ]
