# Generated by Django 3.1.2 on 2020-12-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201216_0626'),
        ('user', '0003_auto_20201216_0613'),
    ]

    operations = [
    ]
