# Generated by Django 3.1.2 on 2020-12-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201216_0710'),
        ('user', '0004_merge_20201216_0711'),
    ]

    operations = [
    ]
