# Generated by Django 3.1.2 on 2020-11-25 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201116_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='style',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.codingstyle'),
        ),
    ]
