# Generated by Django 3.1.2 on 2020-11-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201125_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='group',
        ),
    ]
