# Generated by Django 3.1.2 on 2020-12-16 11:18

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UM', models.FloatField()),
                ('TI', models.FloatField()),
                ('RT', models.FloatField()),
                ('JC', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
                ('code', models.TextField(default='')),
                ('elapsed_time', models.FloatField(default=11.0)),
                ('erase_cnt', models.IntegerField(default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
                ('solution1', models.TextField(default='')),
                ('solution2', models.TextField(default='')),
                ('solution3', models.TextField(default='')),
                ('mean_elapsed_time', models.FloatField(default=0.0)),
                ('mean_erase_cnt', models.IntegerField(default=0)),
                ('style_int', models.IntegerField(default=0)),
                ('style_str', models.CharField(default='', max_length=4)),
                ('UM_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti'), (3, 'Rt'), (4, 'Jc')], default=0)),
                ('UM_probability', models.FloatField(default=0)),
                ('RT_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti'), (3, 'Rt'), (4, 'Jc')], default=0)),
                ('RT_probability', models.FloatField(default=0)),
                ('TI_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti'), (3, 'Rt'), (4, 'Jc')], default=0)),
                ('TI_probability', models.FloatField(default=0)),
                ('JC_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti'), (3, 'Rt'), (4, 'Jc')], default=0)),
                ('JC_probability', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
