# Generated by Django 3.1.2 on 2020-11-22 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0014_auto_20201117_1003'),
        ('group', '0003_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UM', models.FloatField()),
                ('TI', models.FloatField()),
                ('EF', models.FloatField()),
                ('JC', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
                ('solution1', models.TextField()),
                ('solution2', models.TextField()),
                ('UM_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], default=0)),
                ('UM_probability', models.FloatField(default=0)),
                ('EF_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], default=0)),
                ('EF_probability', models.FloatField(default=0)),
                ('TI_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], default=0)),
                ('TI_probability', models.FloatField(default=0)),
                ('JC_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], default=0)),
                ('JC_probability', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
                ('code', models.TextField(default='')),
                ('elapsed_time', models.FloatField(default=11.0)),
                ('erase_cnt', models.IntegerField(default=4)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.solution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.distribution')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.distribution')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.distribution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
