# Generated by Django 3.1.2 on 2020-11-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionreport',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
