# Generated by Django 3.1.2 on 2020-11-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_solutionreport_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionreport',
            name='elapsed_time',
            field=models.FloatField(default=11.0),
        ),
        migrations.AddField(
            model_name='solutionreport',
            name='erase_cnt',
            field=models.IntegerField(default=4),
        ),
    ]
