# Generated by Django 3.1.2 on 2020-12-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20201201_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='style_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userreport',
            name='style_str',
            field=models.CharField(default='', max_length=4),
        ),
    ]
