# Generated by Django 3.1.2 on 2020-11-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20201114_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreport',
            old_name='erase_probability',
            new_name='EF_probability',
        ),
        migrations.RenameField(
            model_name='userreport',
            old_name='ml_probability',
            new_name='JC_probability',
        ),
        migrations.RenameField(
            model_name='userreport',
            old_name='style_probability',
            new_name='TI_probability',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='erase_prediction',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='ml_prediction',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='style_prediction',
        ),
        migrations.AddField(
            model_name='userreport',
            name='EF_prediction',
            field=models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], default=0),
        ),
        migrations.AddField(
            model_name='userreport',
            name='JC_prediction',
            field=models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], default=0),
        ),
        migrations.AddField(
            model_name='userreport',
            name='TI_prediction',
            field=models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], default=0),
        ),
        migrations.AddField(
            model_name='userreport',
            name='UM_prediction',
            field=models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], default=0),
        ),
        migrations.AddField(
            model_name='userreport',
            name='UM_probability',
            field=models.FloatField(default=0),
        ),
    ]
