# Generated by Django 3.1.2 on 2020-11-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20201030_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalreport',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2),
        ),
        migrations.AddField(
            model_name='groupreport',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2),
        ),
        migrations.AddField(
            model_name='problemreport',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2),
        ),
        migrations.AddField(
            model_name='solutionreport',
            name='predcition',
            field=models.IntegerField(choices=[(1, 'Um'), (2, 'Ti'), (3, 'Ef'), (4, 'Jc')], null=True),
        ),
        migrations.AddField(
            model_name='solutionreport',
            name='probability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='solutionreport',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2),
        ),
    ]
