# Generated by Django 3.1.2 on 2020-11-10 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0007_auto_20201109_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionreport',
            name='erase_prediction',
        ),
        migrations.RemoveField(
            model_name='solutionreport',
            name='erase_probability',
        ),
        migrations.RemoveField(
            model_name='solutionreport',
            name='ml_prediction',
        ),
        migrations.RemoveField(
            model_name='solutionreport',
            name='ml_probability',
        ),
        migrations.RemoveField(
            model_name='solutionreport',
            name='style_prediction',
        ),
        migrations.RemoveField(
            model_name='solutionreport',
            name='style_probability',
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'Running'), (3, 'Error')], default=2)),
                ('solution1', models.TextField()),
                ('solution2', models.TextField()),
                ('ml_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], null=True)),
                ('ml_probability', models.FloatField(default=0)),
                ('style_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], null=True)),
                ('style_probability', models.FloatField(default=0)),
                ('erase_prediction', models.IntegerField(choices=[(1, 'Um'), (2, 'Ti')], null=True)),
                ('erase_probability', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
