# Generated by Django 3.1.1 on 2020-09-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codingmbti', '0001_initial'),
    ]

    def insertData(apps, schema_editor):
     Login = apps.get_model('codingmbti', 'Name')
     user = Login(name = "Adam")
     user.save()
     user = Login(name = "Britney")
     user.save()
     user = Login(name = "Cavin")
     user.save()
     user = Login(name = "Druid")
     user.save()
     user = Login(name = "Esther")
     user.save()

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='name',
            name='content',
        ),
        migrations.RemoveField(
            model_name='name',
            name='done',
        ),
        migrations.RunPython(insertData),
    ]
